pull_request_rules:
  - name: auto-approve and merge Dependabot docs updates into dev
    conditions:
      - author = dependabot[bot]
      - base = dev
      - -draft
      - files ~= ^doc/
      - check-success = docs-check
    actions:
      review:
        type: APPROVE
        message: Automatically approving Dependabot docs update after docs CI passes.
      merge:
        method: merge

  - name: auto-approve and merge Dependabot updates into dev
    conditions:
      - author = dependabot[bot]
      - base = dev
      - -draft
      - check-success = validate-monorepo
    actions:
      review:
        type: APPROVE
        message: Automatically approving Dependabot update after all dev CI checks pass.
      merge:
        method: merge
