# ===== Proxy =====
# 按本地环境修改地址和端口
systemProp.http.proxyHost=127.0.0.1
systemProp.http.proxyPort=7899
systemProp.https.proxyHost=127.0.0.1
systemProp.https.proxyPort=7899

# ===== Build Behaviour =====
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.workers.max=5
org.gradle.configureondemand=true

# ===== Cache =====
org.gradle.caching=true
org.gradle.configuration-cache=true

# ===== JVM =====
org.gradle.jvmargs=-Xms1024m -Xmx2048m -XX:+UseParallelGC -XX:MaxMetaspaceSize=512m -Dfile.encoding=UTF-8

# ===== Kotlin =====
kotlin.incremental=true
kotlin.incremental.useClasspathSnapshot=true
kotlin.parallel.tasks.in.project=true
