[versions]
org-jetbrains-kotlin = "2.1.0"
org-jetbrains-kotlinx-coroutines = "1.9.0"
io-ktor = "3.0.2"
com-google-devtools-ksp = "2.1.0-1.0.29"

[libraries]
org-jetbrains-kotlinx-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "org-jetbrains-kotlinx-coroutines" }
org-jetbrains-kotlinx-coroutines-test = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "org-jetbrains-kotlinx-coroutines" }
# BOM 管理：BOM 自身声明 version.ref，其管理的 library 省略 version
io-ktor-bom = { module = "io.ktor:ktor-bom", version.ref = "io-ktor" }
io-ktor-server-core = { module = "io.ktor:ktor-server-core" }
io-ktor-server-netty = { module = "io.ktor:ktor-server-netty" }

[bundles]
io-ktor-server = ["io-ktor-server-core", "io-ktor-server-netty"]

[plugins]
org-jetbrains-kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "org-jetbrains-kotlin" }
org-jetbrains-kotlin-plugin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "org-jetbrains-kotlin" }
com-google-devtools-ksp = { id = "com.google.devtools.ksp", version.ref = "com-google-devtools-ksp" }
