/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdaptorsRouteImport } from './routes/adaptors'
import { Route as ConfigRouteImport } from './routes/config'
import { Route as FilesRouteImport } from './routes/files'
import { Route as LogsRouteImport } from './routes/logs'
import { Route as PipelineRouteImport } from './routes/pipeline'
import { Route as SettingsRouteImport } from './routes/settings'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdaptorsRoute = AdaptorsRouteImport.update({
  id: '/adaptors',
  path: '/adaptors',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfigRoute = ConfigRouteImport.update({
  id: '/config',
  path: '/config',
  getParentRoute: () => rootRouteImport,
} as any)
const FilesRoute = FilesRouteImport.update({
  id: '/files',
  path: '/files',
  getParentRoute: () => rootRouteImport,
} as any)
const LogsRoute = LogsRouteImport.update({
  id: '/logs',
  path: '/logs',
  getParentRoute: () => rootRouteImport,
} as any)
const PipelineRoute = PipelineRouteImport.update({
  id: '/pipeline',
  path: '/pipeline',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/adaptors': typeof AdaptorsRoute
  '/config': typeof ConfigRoute
  '/files': typeof FilesRoute
  '/logs': typeof LogsRoute
  '/pipeline': typeof PipelineRoute
  '/settings': typeof SettingsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/adaptors': typeof AdaptorsRoute
  '/config': typeof ConfigRoute
  '/files': typeof FilesRoute
  '/logs': typeof LogsRoute
  '/pipeline': typeof PipelineRoute
  '/settings': typeof SettingsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/adaptors': typeof AdaptorsRoute
  '/config': typeof ConfigRoute
  '/files': typeof FilesRoute
  '/logs': typeof LogsRoute
  '/pipeline': typeof PipelineRoute
  '/settings': typeof SettingsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/adaptors'
    | '/config'
    | '/files'
    | '/logs'
    | '/pipeline'
    | '/settings'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/adaptors'
    | '/config'
    | '/files'
    | '/logs'
    | '/pipeline'
    | '/settings'
  id:
    | '__root__'
    | '/'
    | '/adaptors'
    | '/config'
    | '/files'
    | '/logs'
    | '/pipeline'
    | '/settings'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdaptorsRoute: typeof AdaptorsRoute
  ConfigRoute: typeof ConfigRoute
  FilesRoute: typeof FilesRoute
  LogsRoute: typeof LogsRoute
  PipelineRoute: typeof PipelineRoute
  SettingsRoute: typeof SettingsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/adaptors': {
      id: '/adaptors'
      path: '/adaptors'
      fullPath: '/adaptors'
      preLoaderRoute: typeof AdaptorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/config': {
      id: '/config'
      path: '/config'
      fullPath: '/config'
      preLoaderRoute: typeof ConfigRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/files': {
      id: '/files'
      path: '/files'
      fullPath: '/files'
      preLoaderRoute: typeof FilesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/logs': {
      id: '/logs'
      path: '/logs'
      fullPath: '/logs'
      preLoaderRoute: typeof LogsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pipeline': {
      id: '/pipeline'
      path: '/pipeline'
      fullPath: '/pipeline'
      preLoaderRoute: typeof PipelineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdaptorsRoute: AdaptorsRoute,
  ConfigRoute: ConfigRoute,
  FilesRoute: FilesRoute,
  LogsRoute: LogsRoute,
  PipelineRoute: PipelineRoute,
  SettingsRoute: SettingsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
