[package]
name = "tnmsc-integrate-tests"
publish = false
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true

[dependencies]
serde_json = { workspace = true }
tar = "0.4"
flate2 = "1"
testcontainers = { version = "0.27.3", features = ["blocking"] }
