/**
 * Aindex validation and generation utilities
 * 使用扁平的 bundles 结构直接遍历创建项目目录和文件
 */
import type {AindexConfig, ILogger} from './adaptors/adaptor-core'
import * as fs from 'node:fs'
import * as path from 'node:path'
import {buildUsageDiagnostic, diagnosticLines} from '@/diagnostics'

/**
 * Version control check result
 */
export interface VersionControlCheckResult {
  readonly hasGit: boolean
  readonly gitPath: string
}

/**
 * Check if the aindex has version control (.git directory)
 * Logs info if .git exists, warns if not
 *
 * @param rootPath - Root path of the aindex
 * @param logger - Optional logger instance
 * @returns Version control check result
 */
export function checkVersionControl(
  rootPath: string,
  logger?: ILogger
): VersionControlCheckResult {
  const gitPath = path.join(rootPath, '.git')
  const hasGit = fs.existsSync(gitPath)

  if (hasGit) logger?.info('version control detected', {path: gitPath})
  else {
    logger?.warn(buildUsageDiagnostic({
      code: 'AINDEX_VERSION_CONTROL_MISSING',
      title: 'Aindex root is not under version control',
      rootCause: diagnosticLines(`tnmsc did not find a .git directory under "${rootPath}".`),
      exactFix: diagnosticLines(
        `Initialize git in "${rootPath}" or place the aindex inside an existing git repository.`
      ),
      possibleFixes: [
        diagnosticLines('Run `git init` in the aindex root if the directory should be versioned.')
      ],
      details: {
        rootPath,
        gitPath
      }
    }))
  }

  return {hasGit, gitPath}
}

/**
 * Generation result
 */
export interface GenerationResult {
  readonly success: boolean
  readonly rootPath: string
  readonly createdDirs: readonly string[]
  readonly createdFiles: readonly string[]
  readonly existedDirs: readonly string[]
  readonly existedFiles: readonly string[]
}

/**
 * Generation options
 */
export interface GenerationOptions {
  /** Logger instance */
  readonly logger?: ILogger
  /** Aindex structure from user config */
  readonly config?: Required<AindexConfig>
}

const DEFAULT_FILE_CONTENT = '# Generated by tnmsc init\n'

function isFilePath(relativePath: string): boolean {
  return path.extname(relativePath).length > 0
}

/**
 * Generate aindex directory structure
 */
export function generateAindex(
  rootPath: string,
  options: GenerationOptions = {}
): GenerationResult {
  const {logger, config} = options
  const createdDirs: string[] = []
  const createdFiles: string[] = []
  const existedDirs: string[] = []
  const existedFiles: string[] = []
  const createdDirsSet = new Set<string>()
  const existedDirsSet = new Set<string>()
  const existedFilesSet = new Set<string>()

  const ensureDirectory = (dirPath: string): void => {
    if (fs.existsSync(dirPath)) {
      if (!existedDirsSet.has(dirPath)) {
        existedDirsSet.add(dirPath)
        existedDirs.push(dirPath)
        logger?.debug('directory exists', {path: dirPath})
      }
      return
    }

    fs.mkdirSync(dirPath, {recursive: true})

    let currentDir = dirPath
    while (!createdDirsSet.has(currentDir)) {
      createdDirsSet.add(currentDir)
      createdDirs.push(currentDir)
      logger?.info('created directory', {path: currentDir})

      if (currentDir === rootPath) break
      currentDir = path.dirname(currentDir)
    }
  }

  const ensureFile = (filePath: string, content: string = DEFAULT_FILE_CONTENT): void => {
    ensureDirectory(path.dirname(filePath))

    if (fs.existsSync(filePath)) {
      if (!existedFilesSet.has(filePath)) {
        existedFilesSet.add(filePath)
        existedFiles.push(filePath)
        logger?.debug('file exists', {path: filePath})
      }
      return
    }

    fs.writeFileSync(filePath, content, 'utf8')
    createdFiles.push(filePath)
    logger?.info('created file', {path: filePath})
  }

  ensureDirectory(rootPath)

  if (config != null) {
    for (const [key, moduleConfig] of Object.entries(config)) {
      if (key === 'dir' || typeof moduleConfig !== 'object' || moduleConfig == null) continue

      for (const relativePath of [moduleConfig.src, moduleConfig.dist]) {
        const targetPath = path.join(rootPath, relativePath)
        if (isFilePath(relativePath)) ensureFile(targetPath)
        else ensureDirectory(targetPath)
      }
    }
  }

  return {
    success: true,
    rootPath,
    createdDirs,
    createdFiles,
    existedDirs,
    existedFiles
  }
}
