[package]
name = "tnmsc-local-tests"
publish = false
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true

[dependencies]
serde_json = { workspace = true }
json5 = { workspace = true }
dirs = { workspace = true }
