name: Build GUI All Platforms

on:
  workflow_call:
    inputs:
      version:
        required: true
        type: string

permissions:
  contents: read

jobs:
  build-all:
    strategy:
      fail-fast: true
      matrix:
        include:
          - os: windows-latest
            platform: windows
          - os: ubuntu-24.04
            platform: linux
          - os: macos-14
            platform: macos
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup-node-pnpm
      - uses: ./.github/actions/setup-tauri
        with:
          version: ${{ inputs.version }}

      - name: Build GUI
        working-directory: ./gui
        env:
          TAURI_SIGNING_PRIVATE_KEY: ${{ secrets.TAURI_SIGNING_PRIVATE_KEY }}
          TAURI_SIGNING_PRIVATE_KEY_PASSWORD: ${{ secrets.TAURI_SIGNING_PRIVATE_KEY_PASSWORD }}
        run: pnpm tauri build

      - name: Upload Windows artifacts
        if: matrix.platform == 'windows'
        uses: actions/upload-artifact@v4
        with:
          name: gui-${{ matrix.os }}
          path: |
            target/*/release/bundle/**/*.exe
            target/release/bundle/**/*.exe
          if-no-files-found: error

      - name: Upload Linux artifacts
        if: matrix.platform == 'linux'
        uses: actions/upload-artifact@v4
        with:
          name: gui-${{ matrix.os }}
          path: |
            target/*/release/bundle/**/*.AppImage
            target/*/release/bundle/**/*.deb
            target/*/release/bundle/**/*.rpm
            target/release/bundle/**/*.AppImage
            target/release/bundle/**/*.deb
            target/release/bundle/**/*.rpm
          if-no-files-found: error

      - name: Upload macOS artifacts
        if: matrix.platform == 'macos'
        uses: actions/upload-artifact@v4
        with:
          name: gui-${{ matrix.os }}
          path: |
            target/*/release/bundle/**/*.dmg
            target/release/bundle/**/*.dmg
          if-no-files-found: error
