name: Build GUI All Platforms

on:
  workflow_call:
    inputs:
      version:
        required: true
        type: string

permissions:
  contents: read

jobs:
  build-all:
    strategy:
      fail-fast: true
      matrix:
        include:
          - os: windows-latest
            rust-targets: ''
            tauri-command: pnpm tauri build
            artifact-path: |
              gui/src-tauri/target/*/release/bundle/**/*.exe
              gui/src-tauri/target/release/bundle/**/*.exe
              gui/src-tauri/target/*/release/bundle/**/*.sig
              gui/src-tauri/target/release/bundle/**/*.sig
          - os: ubuntu-24.04
            rust-targets: ''
            tauri-command: pnpm tauri build
            artifact-path: |
              gui/src-tauri/target/*/release/bundle/**/*.AppImage
              gui/src-tauri/target/*/release/bundle/**/*.deb
              gui/src-tauri/target/*/release/bundle/**/*.rpm
              gui/src-tauri/target/*/release/bundle/**/*.sig
              gui/src-tauri/target/release/bundle/**/*.AppImage
              gui/src-tauri/target/release/bundle/**/*.deb
              gui/src-tauri/target/release/bundle/**/*.rpm
              gui/src-tauri/target/release/bundle/**/*.sig
          - os: macos-14
            rust-targets: aarch64-apple-darwin,x86_64-apple-darwin
            tauri-command: pnpm tauri build --target universal-apple-darwin
            artifact-path: |
              gui/src-tauri/target/*/release/bundle/**/*.dmg
              gui/src-tauri/target/*/release/bundle/**/*.tar.gz
              gui/src-tauri/target/*/release/bundle/**/*.sig
              gui/src-tauri/target/release/bundle/**/*.dmg
              gui/src-tauri/target/release/bundle/**/*.tar.gz
              gui/src-tauri/target/release/bundle/**/*.sig
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v6

      - uses: ./.github/actions/build-gui-platform
        with:
          tauri-command: ${{ matrix.tauri-command }}
          artifact-name: gui-${{ matrix.os }}
          artifact-path: ${{ matrix.artifact-path }}
          rust-targets: ${{ matrix.rust-targets }}
          signing-private-key: ${{ secrets.TAURI_SIGNING_PRIVATE_KEY }}
          signing-private-key-password: ${{ secrets.TAURI_SIGNING_PRIVATE_KEY_PASSWORD }}
          version: ${{ inputs.version }}
